/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    api: [{ type: 'autogenerated', dirName: 'Problems' }],

    DSA: [
        {
            type: 'category',
            label: 'Bit Manipulation',
            link: {
                type: 'generated-index',
                title: 'Bit Manipulation',
                keywords: ['BIT'],
            },
            items: [
                'Problems/DSA/Bit Magic/Prerequisite',
                'Problems/DSA/Bit Magic/Longest_ones_in_binary_representation',
                'Problems/DSA/Bit Magic/NotSoEasyMath',
                'Problems/DSA/Bit Magic/PlayingWithBits',
            ]
        },
        {
            type: 'category',
            label: 'Number Theory',
            link: {
                type: 'generated-index',
                title: 'Number Theory',
                keywords: ['Number Theory'],
            },
            items: [
                'Problems/DSA/NumberTheory/Exponentiation',
                'Problems/DSA/NumberTheory/ModularExponentiation',
            ]
        },
        {
            type: 'category',
            label: 'Trees',
            link: {
                type: 'generated-index',
                title: 'Trees',
                keywords: ['Trees'],
            },
            items: [
                'Problems/DSA/Trees/Maximum_Binary_Tree',
            ]
        }
    ],

    Leetcode: [
        {
            type: 'category',
            label: 'Leetcode for Placement',
            link: {
                type: 'generated-index',
                title: 'Leetcode for Placement',
                keywords: ['Placement'],
            },
            items: [
                'Problems/Interviews/Introduction',
                'Problems/Interviews/Amazon',
                'Problems/Interviews/Facebook',
                'Problems/Interviews/Google',
                'Problems/Interviews/Linkedln',
                'Problems/Interviews/Top 50 Interview questions',
            ]
        },
        {
            type: 'category',
            label: 'Striver Sheet',
            link: {
                type: 'generated-index',
                title: 'Striver DSA Sheets',
                description:
                    "SDE and DP sheet by Stiver",
                keywords: ['Striver'],
            },
            items: [
                {
                    type: 'category',
                    label: 'Striver SDE Sheet',
                    link: {
                        type: 'generated-index',
                        title: 'Striver SDE Sheet',
                        description:
                            "SDE by Stiver",
                    },
                    items: [
                        {
                            "type": "category",
                            "label": "Arrays",
                            "link": {
                                "type": "generated-index",
                                "title": "Arrays"
                            },
                            "items": [
                                "codes/pascals-triangle",
                                "codes/next-permutation",
                                "codes/set-matrix-zeroes",
                                "codes/best-time-to-buy-and-sell-stock",
                                "codes/maximum-subarray",
                                "codes/sort-colors"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Arrays Part-II",
                            "link": {
                                "type": "generated-index",
                                "title": "Arrays Part-II"
                            },
                            "items": [
                                "codes/merge-intervals",
                                "codes/merge-sorted-array",
                                "codes/repeat-and-missing-number-array",
                                "codes/rotate-image",
                                "codes/count-inversions",
                                "codes/find-the-duplicate-number"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Arrays Part-III",
                            "link": {
                                "type": "generated-index",
                                "title": "Arrays Part-III"
                            },
                            "items": [
                                "codes/reverse-pairs",
                                "codes/search-a-2d-matrix",
                                "codes/powx-n",
                                "codes/majority-element-ii",
                                "codes/unique-paths",
                                "codes/majority-element"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Arrays Part-IV",
                            "link": {
                                "type": "generated-index",
                                "title": "Arrays Part-IV"
                            },
                            "items": [
                                "codes/4sum",
                                "codes/longest-consecutive-sequence",
                                "codes/subarray-with-given-xor",
                                "codes/longest-subarray-zero-sum",
                                "codes/two-sum",
                                "codes/longest-substring-without-repeating-characters"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Linked List",
                            "link": {
                                "type": "generated-index",
                                "title": "Linked List"
                            },
                            "items": [
                                "codes/add-two-numbers",
                                "codes/delete-node-in-a-linked-list",
                                "codes/reverse-linked-list",
                                "codes/middle-of-the-linked-list",
                                "codes/merge-two-sorted-lists",
                                "codes/remove-nth-node-from-end-of-list"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Linked List Part-II",
                            "link": {
                                "type": "generated-index",
                                "title": "Linked List Part-II"
                            },
                            "items": [
                                "codes/palindrome-linked-list",
                                "codes/flattening-a-linked-list",
                                "codes/linked-list-cycle",
                                "codes/reverse-nodes-in-k-group",
                                "codes/intersection-of-two-linked-lists",
                                "codes/linked-list-cycle-ii"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Linked List and Arrays",
                            "link": {
                                "type": "generated-index",
                                "title": "Linked List and Arrays"
                            },
                            "items": [
                                "codes/trapping-rain-water",
                                "codes/max-consecutive-ones",
                                "codes/remove-duplicates-from-sorted-array",
                                "codes/3Sum",
                                "codes/copy-list-with-random-pointer",
                                "codes/rotate-list"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Greedy Algorithm",
                            "link": {
                                "type": "generated-index",
                                "title": "Greedy Algorithm"
                            },
                            "items": [
                                "codes/minimum-platforms",
                                "codes/job-sequencing-problem",
                                "codes/number-of-coins",
                                "codes/maximum-meetings",
                                "codes/fractional-knapsack"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Recursion",
                            "link": {
                                "type": "generated-index",
                                "title": "Recursion"
                            },
                            "items": [
                                "codes/combination-sum-ii",
                                "codes/subset-sums",
                                "codes/permutation-sequence",
                                "codes/combination-sum",
                                "codes/subsets-ii",
                                "codes/palindrome-partitioning"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Recursion and Backtracking",
                            "link": {
                                "type": "generated-index",
                                "title": "Recursion and Backtracking"
                            },
                            "items": [
                                "codes/sudoku-solver",
                                "codes/word-break",
                                "codes/rat-in-a-maze-problemI",
                                "codes/n-queens",
                                "codes/m-coloring-problem",
                                "codes/permutations"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Binary Search",
                            "link": {
                                "type": "generated-index",
                                "title": "Binary Search"
                            },
                            "items": [
                                "codes/allocate-books",
                                "codes/k-th-element-of-two-sorted-array",
                                "codes/median-of-two-sorted-arrays",
                                "codes/nth-root-of-m",
                                "codes/single-element-in-a-sorted-array",
                                "codes/matrix-median",
                                "codes/search-in-rotated-sorted-array",
                                "codes/chess-tournament"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Heaps",
                            "link": {
                                "type": "generated-index",
                                "title": "Heaps"
                            },
                            "items": [
                                "codes/merge-k-sorted-arrays",
                                "codes/kth-largest-element-in-an-array",
                                "codes/top-k-frequent-elements",
                                "codes/maximum-sum-combinations",
                                "codes/find-median-from-data-stream"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Stack and Queue",
                            "link": {
                                "type": "generated-index",
                                "title": "Stack and Queue"
                            },
                            "items": [
                                "codes/implement-a-queue-using-array",
                                "codes/next-greater-element-i",
                                "codes/implement-stack-using-queues",
                                "codes/implement-a-stack-using-arrays",
                                "codes/implement-queue-using-stacks",
                                "codes/sort-a-stack",
                                "codes/valid-parentheses"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Stack and Queue Part-II",
                            "link": {
                                "type": "generated-index",
                                "title": "Stack and Queue Part-II"
                            },
                            "items": [
                                "codes/sliding-window-maximum",
                                "codes/nearest-smaller-element",
                                "codes/rotting-oranges",
                                "codes/lfu-cache",
                                "codes/online-stock-span",
                                "codes/min-stack",
                                "codes/lru-cache",
                                "codes/largest-rectangle-in-histogram",
                                "codes/the-celebrity-problem"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "String",
                            "link": {
                                "type": "generated-index",
                                "title": "String"
                            },
                            "items": [
                                "codes/reverse-words-in-a-string",
                                "codes/repeated-string-match",
                                "codes/string-to-integer-atoi",
                                "codes/roman-to-integer",
                                "codes/longest-palindromic-substring",
                                "codes/longest-common-prefix"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "String-II",
                            "link": {
                                "type": "generated-index",
                                "title": "String-II"
                            },
                            "items": [
                                "codes/valid-anagram",
                                "codes/minimum-characters-required-to-make-a-string-palindromic",
                                "codes/implement-strstr",
                                "codes/compare-version-numbers",
                                "codes/count-and-say"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Binary Tree",
                            "link": {
                                "type": "generated-index",
                                "title": "Binary Tree"
                            },
                            "items": [
                                "codes/binary-tree-preorder-traversal",
                                "codes/left-view-of-binary-tree",
                                "codes/tree-traversals",
                                "codes/maximum-width-of-binary-tree",
                                "codes/binary-tree-postorder-traversal",
                                "codes/binary-tree-preorder-traversal",
                                "codes/path-to-given-node",
                                "codes/vertical-order-traversal-of-a-binary-tree",
                                "codes/binary-tree-inorder-traversal",
                                "codes/top-view-of-binary-tree",
                                "codes/bottom-view-of-binary-tree",
                                "codes/binary-tree-inorder-traversal"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Binary Tree Part-II",
                            "link": {
                                "type": "generated-index",
                                "title": "Binary Tree Part-II"
                            },
                            "items": [
                                "codes/binary-tree-zigzag-level-order-traversal",
                                "codes/binary-tree-level-order-traversal",
                                "codes/boundary-traversal-of-binary-tree",
                                "codes/lowest-common-ancestor-of-a-binary-tree",
                                "codes/same-tree",
                                "codes/maximum-depth-of-binary-tree",
                                "codes/balanced-binary-tree",
                                "codes/diameter-of-binary-tree"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Binary Tree part-III",
                            "link": {
                                "type": "generated-index",
                                "title": "Binary Tree part-III"
                            },
                            "items": [
                                "codes/construct-binary-tree-from-preorder-and-inorder-traversal",
                                "codes/construct-binary-tree-from-inorder-and-postorder-traversal",
                                "codes/symmetric-tree",
                                "codes/flatten-binary-tree-to-linked-list",
                                "codes/children-sum-property",
                                "codes/binary-tree-maximum-path-sum",
                                "codes/mirror-tree"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Binary Search Tree",
                            "link": {
                                "type": "generated-index",
                                "title": "Binary Search Tree"
                            },
                            "items": [
                                "codes/lowest-common-ancestor-of-a-binary-search-tree",
                                "codes/search-in-a-binary-search-tree",
                                "codes/construct-binary-search-tree-from-preorder-traversal",
                                "codes/validate-binary-search-tree",
                                "codes/convert-sorted-array-to-binary-search-tree",
                                "codes/populating-next-right-pointers-in-each-node"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Binary Search Tree Part-II",
                            "link": {
                                "type": "generated-index",
                                "title": "Binary Search Tree Part-II"
                            },
                            "items": [
                                "codes/two-sum-iv-input-is-a-bst",
                                "codes/kth-largest-element-in-bst",
                                "codes/maximum-sum-bst-in-binary-tree",
                                "codes/binary-search-tree-iterator",
                                "codes/ceil-from-bst",
                                "codes/kth-smallest-element-in-a-bst",
                                "codes/serialize-and-deserialize-binary-tree",
                                "codes/floor-in-bst"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Binary Trees[Miscellaneous]",
                            "link": {
                                "type": "generated-index",
                                "title": "Binary Trees[Miscellaneous]"
                            },
                            "items": [
                                "codes/kth-largest-element-in-an-array",
                                "codes/flood-fill",
                                "codes/distinct-numbers-in-window",
                                "codes/flatten-binary-tree-to-linked-list",
                                "codes/kth-largest-element-in-a-stream",
                                "codes/find-median-from-data-stream"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Graph",
                            "link": {
                                "type": "generated-index",
                                "title": "Graph"
                            },
                            "items": [
                                "codes/is-graph-bipartite",
                                "codes/number-of-islands",
                                "codes/course-schedule",
                                "codes/clone-graph",
                                "codes/depth-first-traversal-for-a-graph",
                                "codes/topological-sort",
                                "codes/bfs-traversal-of-graph"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Graph Part-II",
                            "link": {
                                "type": "generated-index",
                                "title": "Graph Part-II"
                            },
                            "items": [
                                "codes/maximum-number-of-non-overlapping-substrings",
                                "codes/implementing-dijkstra-set-1-adjacency-matrix",
                                "codes/implementing-floyd-warshall",
                                "codes/distance-from-the-source-bellman-ford-algorithm",
                                "codes/minimum-spanning-tree"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Dynamic Programming",
                            "link": {
                                "type": "generated-index",
                                "title": "Dynamic Programming"
                            },
                            "items": [
                                "codes/longest-increasing-subsequence",
                                "codes/longest-common-subsequence",
                                "codes/ones-and-zeroes",
                                "codes/matrix-chain-multiplication",
                                "codes/edit-distance",
                                "codes/maximum-sum-increasing-subsequence",
                                "codes/maximum-product-subarray"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Dynamic Programming Part-II",
                            "link": {
                                "type": "generated-index",
                                "title": "Dynamic Programming Part-II"
                            },
                            "items": [
                                "codes/word-break",
                                "codes/partition-equal-subset-sum",
                                "codes/maximum-profit-in-job-scheduling",
                                "codes/minimum-path-sum",
                                "codes/coin-change",
                                "codes/palindrome-partitioning",
                                "codes/minimum-cost-to-cut-a-stick",
                                "codes/super-egg-drop"
                            ]
                        },
                        {
                            "type": "category",
                            "label": "Trie",
                            "link": {
                                "type": "generated-index",
                                "title": "Trie"
                            },
                            "items": [
                                "codes/subsets",
                                "codes/maximum-xor-of-two-numbers-in-an-array",
                                "codes/implement-trie-prefix-tree",
                                "codes/maximum-xor-with-an-element-from-array"
                            ]
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Striver DP Sheet',
                    link: {
                        type: 'generated-index',
                        title: 'Striver DP Sheet',
                    },
                    items: [
                        {
                            type: 'category',
                            label: '1D DP',
                            link: {
                                type: 'generated-index',
                                title: '1D DP',
                            },
                            items: [
                                'codes/climbing-stairs',
                                'codes/frog-with-k-jumps',
                                'codes/maximum-sum-of-non-adjacent-elements',
                                'codes/house-robber',
                                'codes/house-robber-ii',
                            ]
                        },

                    ]
                },
                {
                    type: 'category',
                    label: 'Blind 75',
                    link: {
                        type: 'generated-index',
                        title: 'Blind 75',
                    },
                    items: [
                        {
                            type: 'category',
                            label: 'Arrays',
                            link: {
                                type: 'generated-index',
                                title: 'Arrays',
                            },
                            items: [
                                'codes/two-sum',
                                'codes/best-time-to-buy-and-sell-stock',
                                'codes/contains-duplicate',
                                'codes/product-of-array-except-self',
                                'codes/maximum-subarray',
                                'codes/maximum-product-subarray',
                                'codes/find-minimum-in-rotated-sorted-array',
                                'codes/find-minimum-in-rotated-sorted-array-ii',
                                'codes/search-in-rotated-sorted-array',
                                'codes/3Sum',
                                'codes/container-with-most-water',

                            ]
                        },
                    ]
                },
            ],
        },
    ],

    About: [
        'Problems/intro',
    ],

    Projects: [
        'Problems/intro',
    ],

    ProjectEuler: [
        'Problems/ProjectEuler/start',
    ],


};

module.exports = sidebars;
